spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://121.196.54.2:3306/deniszhong?useUnicode=true&useSSL=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 2
      max-active: 4
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: deniszhong
        login-password: 123456
        reset-enable: false #是否允许清空统计数据
        allow: 127.0.0.1
        deny: 172.16.5.11
        enabled: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
  mail:
    host: smtp.163.com
    username: god_world@163.com
    password: ERZKJIXAYFKIOBSC
    port: 25
  rabbitmq:
    host: 121.196.54.2
    port: 5672
    virtual-host: /
    password: guest
    username: guest
  redis:
    host: 121.196.54.2
    port: 6379

#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      force-request: true

mybatis:
  type-aliases-package: com.denis.zhong.world.entity
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml

server:
  port: 9090
